### ISSUE TITLE
env -h not a valid option

### ISSUE THREAD

**Issue by jrwrigh** [zpm-zsh/colorize#1]
I keep getting an error from `env` saying 

```
➜ env                                      
env: invalid option -- 'h'
Try 'env --help' for more information.
```

I'm not sure why the `-h` flag is invoked in this plugin. Perhaps you could shed some light on that? Otherwise I'm pretty sure it doesn't need to be there.

Edit: I can confirm that removing the `-h` flag doesn't appear to change anything. Output is still colorized.

**Comment by grigorii-horos** [comment]
@jrwrigh merged

**Comment by grigorii-horos** [comment]
@jrwrigh Thank you
