### ISSUE TITLE
[question] Change function diff

### ISSUE THREAD

**Issue by Freed-Wu** [zpm-zsh/colorize#8]
```zsh
if (( $+commands[diff-so-fancy] )); then
  function diff() {
    command diff "$@" | diff-so-fancy
  }
elif (( $+commands[delta] )); then
  function diff() {
    command diff "$@" | delta
  }
else
  function diff() {
    command diff --color "$@"
  }
fi
```

In fact, if user installed delta,

```
❯ echo a > a
❯ echo b > b
❯ command diff a b
1c1
< a
---
> b
❯ command diff a b | delta
1c1
< a
---
> b
❯ command diff -u a b
--- a   2021-08-30 17:24:50.801599241 +0800
+++ b   2021-08-30 17:24:53.541625220 +0800
@@ -1 +1 @@
-a
+b
❯ command diff -u a b|delta
comparing: a ⟶   b
─────────────────────────────────────────

──────┐
Δ :1: │
──────┘
│ 1  │a             │    │
│    │              │ 1  │b
❯ delta a b
comparing: a ⟶   b
─────────────────────────────────────────

──────┐
Δ :1: │
──────┘
│ 1  │a             │    │
│    │              │ 1  │b
```

`command diff a b|delta` is same as `command diff a b`.
So it is unnecessary to add this function.

For
```zsh
function diff() {
  command diff -u "$@" | delta
}
```

I think it is unnecessary, too. Because `delta a b` is same, it just like
```
alias diff=delta
```

So, I think
```zsh
    function diff() {
      command diff --color "$@"
    }
```

is enough for everyone.

PS: in `man diff`

```
       --color[=WHEN]
              color output; WHEN is 'never', 'always', or 'auto'; plain --color means --color='auto'
```

**Comment by builder555** [comment]
fails on a mac:
```
diff: unrecognized option `--color'
diff: Try `diff --help' for more information.
```

**Comment by Freed-Wu** [comment]
I don't have any mac, so I only can guess the reason: maybe it is because mac use BSD's diff not GNU's diff? I heard about many cases resulted from the difference between BSD's command and GNU's command. If so, install a GNU's diff and make it is before BSD's diff in PATH can solve the problem. If not, the code should be updated to detect OSTYPE to decide whether to run the code about diff.

**Comment by builder555** [comment]
@Freed-Wu yup, I created a [PR](https://github.com/zpm-zsh/colorize/pull/11) for that.

**Comment by Freed-Wu** [comment]
I suggest to use `$OSTYPE == darwin` to replace `uname` because OSTYPE is a environment variable, but uname is a extern program, which means it will be slower than detecting OSTYPE.
